/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccessRouteImport } from './routes/access'
import { Route as AnalysisRouteImport } from './routes/analysis'
import { Route as AuditRouteImport } from './routes/audit'
import { Route as FactsRouteImport } from './routes/facts'
import { Route as KnowledgeRouteImport } from './routes/knowledge'
import { Route as OperationsRouteImport } from './routes/operations'
import { Route as ReplayRouteImport } from './routes/replay'
import { Route as ReviewsRouteImport } from './routes/reviews'
import { Route as SandboxRouteImport } from './routes/sandbox'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SystemRouteImport } from './routes/system'
import { Route as WorkspacesRouteImport } from './routes/workspaces'
import { Route as AcquisitionIndexRouteImport } from './routes/acquisition.index'
import { Route as AcquisitionAttemptIdRouteImport } from './routes/acquisition.$attemptId'
import { Route as CasesIndexRouteImport } from './routes/cases.index'
import { Route as CasesCaseIdRouteImport } from './routes/cases.$caseId'
import { Route as DocumentsIndexRouteImport } from './routes/documents.index'
import { Route as DocumentsDocumentIdRouteImport } from './routes/documents.$documentId'
import { Route as SourcesIndexRouteImport } from './routes/sources.index'
import { Route as SourcesSourceIdRouteImport } from './routes/sources.$sourceId'
import { Route as SourcesSourceIdIndexRouteImport } from './routes/sources.$sourceId.index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccessRoute = AccessRouteImport.update({
  id: '/access',
  path: '/access',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalysisRoute = AnalysisRouteImport.update({
  id: '/analysis',
  path: '/analysis',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditRoute = AuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const FactsRoute = FactsRouteImport.update({
  id: '/facts',
  path: '/facts',
  getParentRoute: () => rootRouteImport,
} as any)
const KnowledgeRoute = KnowledgeRouteImport.update({
  id: '/knowledge',
  path: '/knowledge',
  getParentRoute: () => rootRouteImport,
} as any)
const OperationsRoute = OperationsRouteImport.update({
  id: '/operations',
  path: '/operations',
  getParentRoute: () => rootRouteImport,
} as any)
const ReplayRoute = ReplayRouteImport.update({
  id: '/replay',
  path: '/replay',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewsRoute = ReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const SandboxRoute = SandboxRouteImport.update({
  id: '/sandbox',
  path: '/sandbox',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SystemRoute = SystemRouteImport.update({
  id: '/system',
  path: '/system',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspacesRoute = WorkspacesRouteImport.update({
  id: '/workspaces',
  path: '/workspaces',
  getParentRoute: () => rootRouteImport,
} as any)
const AcquisitionIndexRoute = AcquisitionIndexRouteImport.update({
  id: '/acquisition/',
  path: '/acquisition/',
  getParentRoute: () => rootRouteImport,
} as any)
const AcquisitionAttemptIdRoute = AcquisitionAttemptIdRouteImport.update({
  id: '/acquisition/$attemptId',
  path: '/acquisition/$attemptId',
  getParentRoute: () => rootRouteImport,
} as any)
const CasesIndexRoute = CasesIndexRouteImport.update({
  id: '/cases/',
  path: '/cases/',
  getParentRoute: () => rootRouteImport,
} as any)
const CasesCaseIdRoute = CasesCaseIdRouteImport.update({
  id: '/cases/$caseId',
  path: '/cases/$caseId',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsIndexRoute = DocumentsIndexRouteImport.update({
  id: '/documents/',
  path: '/documents/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsDocumentIdRoute = DocumentsDocumentIdRouteImport.update({
  id: '/documents/$documentId',
  path: '/documents/$documentId',
  getParentRoute: () => rootRouteImport,
} as any)
const SourcesIndexRoute = SourcesIndexRouteImport.update({
  id: '/sources/',
  path: '/sources/',
  getParentRoute: () => rootRouteImport,
} as any)
const SourcesSourceIdRoute = SourcesSourceIdRouteImport.update({
  id: '/sources/$sourceId',
  path: '/sources/$sourceId',
  getParentRoute: () => rootRouteImport,
} as any)
const SourcesSourceIdIndexRoute = SourcesSourceIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SourcesSourceIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/access': typeof AccessRoute
  '/analysis': typeof AnalysisRoute
  '/audit': typeof AuditRoute
  '/facts': typeof FactsRoute
  '/knowledge': typeof KnowledgeRoute
  '/operations': typeof OperationsRoute
  '/replay': typeof ReplayRoute
  '/reviews': typeof ReviewsRoute
  '/sandbox': typeof SandboxRoute
  '/settings': typeof SettingsRoute
  '/system': typeof SystemRoute
  '/workspaces': typeof WorkspacesRoute
  '/acquisition/$attemptId': typeof AcquisitionAttemptIdRoute
  '/cases/$caseId': typeof CasesCaseIdRoute
  '/documents/$documentId': typeof DocumentsDocumentIdRoute
  '/sources/$sourceId': typeof SourcesSourceIdRouteWithChildren
  '/acquisition/': typeof AcquisitionIndexRoute
  '/cases/': typeof CasesIndexRoute
  '/documents/': typeof DocumentsIndexRoute
  '/sources/': typeof SourcesIndexRoute
  '/sources/$sourceId/': typeof SourcesSourceIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/access': typeof AccessRoute
  '/analysis': typeof AnalysisRoute
  '/audit': typeof AuditRoute
  '/facts': typeof FactsRoute
  '/knowledge': typeof KnowledgeRoute
  '/operations': typeof OperationsRoute
  '/replay': typeof ReplayRoute
  '/reviews': typeof ReviewsRoute
  '/sandbox': typeof SandboxRoute
  '/settings': typeof SettingsRoute
  '/system': typeof SystemRoute
  '/workspaces': typeof WorkspacesRoute
  '/acquisition/$attemptId': typeof AcquisitionAttemptIdRoute
  '/cases/$caseId': typeof CasesCaseIdRoute
  '/documents/$documentId': typeof DocumentsDocumentIdRoute
  '/acquisition': typeof AcquisitionIndexRoute
  '/cases': typeof CasesIndexRoute
  '/documents': typeof DocumentsIndexRoute
  '/sources': typeof SourcesIndexRoute
  '/sources/$sourceId': typeof SourcesSourceIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/access': typeof AccessRoute
  '/analysis': typeof AnalysisRoute
  '/audit': typeof AuditRoute
  '/facts': typeof FactsRoute
  '/knowledge': typeof KnowledgeRoute
  '/operations': typeof OperationsRoute
  '/replay': typeof ReplayRoute
  '/reviews': typeof ReviewsRoute
  '/sandbox': typeof SandboxRoute
  '/settings': typeof SettingsRoute
  '/system': typeof SystemRoute
  '/workspaces': typeof WorkspacesRoute
  '/acquisition/$attemptId': typeof AcquisitionAttemptIdRoute
  '/cases/$caseId': typeof CasesCaseIdRoute
  '/documents/$documentId': typeof DocumentsDocumentIdRoute
  '/sources/$sourceId': typeof SourcesSourceIdRouteWithChildren
  '/acquisition/': typeof AcquisitionIndexRoute
  '/cases/': typeof CasesIndexRoute
  '/documents/': typeof DocumentsIndexRoute
  '/sources/': typeof SourcesIndexRoute
  '/sources/$sourceId/': typeof SourcesSourceIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/access'
    | '/analysis'
    | '/audit'
    | '/facts'
    | '/knowledge'
    | '/operations'
    | '/replay'
    | '/reviews'
    | '/sandbox'
    | '/settings'
    | '/system'
    | '/workspaces'
    | '/acquisition/$attemptId'
    | '/cases/$caseId'
    | '/documents/$documentId'
    | '/sources/$sourceId'
    | '/acquisition/'
    | '/cases/'
    | '/documents/'
    | '/sources/'
    | '/sources/$sourceId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/access'
    | '/analysis'
    | '/audit'
    | '/facts'
    | '/knowledge'
    | '/operations'
    | '/replay'
    | '/reviews'
    | '/sandbox'
    | '/settings'
    | '/system'
    | '/workspaces'
    | '/acquisition/$attemptId'
    | '/cases/$caseId'
    | '/documents/$documentId'
    | '/acquisition'
    | '/cases'
    | '/documents'
    | '/sources'
    | '/sources/$sourceId'
  id:
    | '__root__'
    | '/'
    | '/access'
    | '/analysis'
    | '/audit'
    | '/facts'
    | '/knowledge'
    | '/operations'
    | '/replay'
    | '/reviews'
    | '/sandbox'
    | '/settings'
    | '/system'
    | '/workspaces'
    | '/acquisition/$attemptId'
    | '/cases/$caseId'
    | '/documents/$documentId'
    | '/sources/$sourceId'
    | '/acquisition/'
    | '/cases/'
    | '/documents/'
    | '/sources/'
    | '/sources/$sourceId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccessRoute: typeof AccessRoute
  AnalysisRoute: typeof AnalysisRoute
  AuditRoute: typeof AuditRoute
  FactsRoute: typeof FactsRoute
  KnowledgeRoute: typeof KnowledgeRoute
  OperationsRoute: typeof OperationsRoute
  ReplayRoute: typeof ReplayRoute
  ReviewsRoute: typeof ReviewsRoute
  SandboxRoute: typeof SandboxRoute
  SettingsRoute: typeof SettingsRoute
  SystemRoute: typeof SystemRoute
  WorkspacesRoute: typeof WorkspacesRoute
  AcquisitionAttemptIdRoute: typeof AcquisitionAttemptIdRoute
  CasesCaseIdRoute: typeof CasesCaseIdRoute
  DocumentsDocumentIdRoute: typeof DocumentsDocumentIdRoute
  SourcesSourceIdRoute: typeof SourcesSourceIdRouteWithChildren
  AcquisitionIndexRoute: typeof AcquisitionIndexRoute
  CasesIndexRoute: typeof CasesIndexRoute
  DocumentsIndexRoute: typeof DocumentsIndexRoute
  SourcesIndexRoute: typeof SourcesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/access': {
      id: '/access'
      path: '/access'
      fullPath: '/access'
      preLoaderRoute: typeof AccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analysis': {
      id: '/analysis'
      path: '/analysis'
      fullPath: '/analysis'
      preLoaderRoute: typeof AnalysisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit': {
      id: '/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/facts': {
      id: '/facts'
      path: '/facts'
      fullPath: '/facts'
      preLoaderRoute: typeof FactsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/knowledge': {
      id: '/knowledge'
      path: '/knowledge'
      fullPath: '/knowledge'
      preLoaderRoute: typeof KnowledgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operations': {
      id: '/operations'
      path: '/operations'
      fullPath: '/operations'
      preLoaderRoute: typeof OperationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/replay': {
      id: '/replay'
      path: '/replay'
      fullPath: '/replay'
      preLoaderRoute: typeof ReplayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reviews': {
      id: '/reviews'
      path: '/reviews'
      fullPath: '/reviews'
      preLoaderRoute: typeof ReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sandbox': {
      id: '/sandbox'
      path: '/sandbox'
      fullPath: '/sandbox'
      preLoaderRoute: typeof SandboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/system': {
      id: '/system'
      path: '/system'
      fullPath: '/system'
      preLoaderRoute: typeof SystemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workspaces': {
      id: '/workspaces'
      path: '/workspaces'
      fullPath: '/workspaces'
      preLoaderRoute: typeof WorkspacesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/acquisition/': {
      id: '/acquisition/'
      path: '/acquisition'
      fullPath: '/acquisition/'
      preLoaderRoute: typeof AcquisitionIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/acquisition/$attemptId': {
      id: '/acquisition/$attemptId'
      path: '/acquisition/$attemptId'
      fullPath: '/acquisition/$attemptId'
      preLoaderRoute: typeof AcquisitionAttemptIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cases/': {
      id: '/cases/'
      path: '/cases'
      fullPath: '/cases/'
      preLoaderRoute: typeof CasesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cases/$caseId': {
      id: '/cases/$caseId'
      path: '/cases/$caseId'
      fullPath: '/cases/$caseId'
      preLoaderRoute: typeof CasesCaseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents/': {
      id: '/documents/'
      path: '/documents'
      fullPath: '/documents/'
      preLoaderRoute: typeof DocumentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents/$documentId': {
      id: '/documents/$documentId'
      path: '/documents/$documentId'
      fullPath: '/documents/$documentId'
      preLoaderRoute: typeof DocumentsDocumentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sources/': {
      id: '/sources/'
      path: '/sources'
      fullPath: '/sources/'
      preLoaderRoute: typeof SourcesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sources/$sourceId': {
      id: '/sources/$sourceId'
      path: '/sources/$sourceId'
      fullPath: '/sources/$sourceId'
      preLoaderRoute: typeof SourcesSourceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sources/$sourceId/': {
      id: '/sources/$sourceId/'
      path: '/'
      fullPath: '/sources/$sourceId/'
      preLoaderRoute: typeof SourcesSourceIdIndexRouteImport
      parentRoute: typeof SourcesSourceIdRoute
    }
  }
}

interface SourcesSourceIdRouteChildren {
  SourcesSourceIdIndexRoute: typeof SourcesSourceIdIndexRoute
}

const SourcesSourceIdRouteChildren: SourcesSourceIdRouteChildren = {
  SourcesSourceIdIndexRoute: SourcesSourceIdIndexRoute,
}

const SourcesSourceIdRouteWithChildren = SourcesSourceIdRoute._addFileChildren(
  SourcesSourceIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccessRoute: AccessRoute,
  AnalysisRoute: AnalysisRoute,
  AuditRoute: AuditRoute,
  FactsRoute: FactsRoute,
  KnowledgeRoute: KnowledgeRoute,
  OperationsRoute: OperationsRoute,
  ReplayRoute: ReplayRoute,
  ReviewsRoute: ReviewsRoute,
  SandboxRoute: SandboxRoute,
  SettingsRoute: SettingsRoute,
  SystemRoute: SystemRoute,
  WorkspacesRoute: WorkspacesRoute,
  AcquisitionAttemptIdRoute: AcquisitionAttemptIdRoute,
  CasesCaseIdRoute: CasesCaseIdRoute,
  DocumentsDocumentIdRoute: DocumentsDocumentIdRoute,
  SourcesSourceIdRoute: SourcesSourceIdRouteWithChildren,
  AcquisitionIndexRoute: AcquisitionIndexRoute,
  CasesIndexRoute: CasesIndexRoute,
  DocumentsIndexRoute: DocumentsIndexRoute,
  SourcesIndexRoute: SourcesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
